.docker:
  stage: build
  script:
    - docker build --tag ${DOCKER_IMAGE}
                   --label build_url=${CI_PROJECT_URL}/pipeline/${CI_PIPELINE_ID}
                   .
    - docker tag      ${DOCKER_IMAGE} ${DOCKER_REGISTRY}/${DOCKER_IMAGE}
    - docker push                     ${DOCKER_REGISTRY}/${DOCKER_IMAGE}
  tags:
    - diceops
    - docker
  image: docker:${DOCKER_VERSION}
  only:
    - master

.docker-ci:
  stage: build
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build --tag ${DOCKER_IMAGE}
                   --label build_url=${CI_PROJECT_URL}/pipeline/${CI_PIPELINE_ID}
                   .
    - docker tag      ${DOCKER_IMAGE} ${CI_REGISTRY}/${DOCKER_IMAGE}
    - docker push                     ${CI_REGISTRY}/${DOCKER_IMAGE}
  tags:
    - diceops
    - docker
  image: docker:${DOCKER_VERSION}
  only:
    - master
