include: '.gitlab-ci-docker.yml'

stages:
  - build

snapshot:
  extends: .docker
  variables:
    DOCKER_IMAGE: ${DOCKER_REGISTRY}/go_starter:snapshot

release:
  extends: .docker
  variables:
    VERSION: ${CI_COMMIT_TAG}
    DOCKER_IMAGE: ${DOCKER_REGISTRY}/go_starter:${CI_COMMIT_TAG}
  only:
    - tags
